import { initTabOrder } from './tab-order.js';
import { initTabs } from './tabs.js';
import { initHome } from './home.js';
import { initLamp } from './lamp.js';
import { initSchedule } from './schedule.js';
import { initDrive } from './drive.js';
import { initMusic } from './music.js';
import { initMedia } from './media.js';
import { initZotifySettings } from './zotify-settings.js';
import { initSettings } from './settings.js';

initHome();
initLamp();
initSchedule();
initDrive();
initMusic();
initMedia();
initZotifySettings();
initSettings();
initTabOrder();
initTabs();
